version: "3.4"
services:
  3hree1nec:
    container_name: 3hree1nec
    build: ./client/
    ports:
      - 3003:3003
  3hree1nes:
    container_name: 3hree1nes
    build: ./server/
    ports:
      - 4003:4003
